language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=traviz CXX=g++-4.8
  global:
    - CC_TEST_REPORTER_ID=eced175fbf4feab32d69333b7af4e9bc0db85821d72c34022de697846a0fd7b1